
POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "Bejeweled",
  "player": "alice",
  "rating": 5,
  "ratedOn": "2025-04-09T12:00:00Z"
}

###
GET http://localhost:8080/api/rating/average/bejeweled
Accept: application/json

###
GET http://localhost:8080/api/rating/bejeweled/alice
Accept: application/json






